name: Check

on:
  push:
    branches: [main]
  workflow_dispatch:


env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  build-docker-image:
    name: Build docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v2

      - uses: benjlevesque/short-sha@v1.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.DOCKER_REGISTRY }}

      - name: Node liveness probe
        uses: docker/build-push-action@v3
        with:
          push: true
          context: images/node-liveness-probe
          tags: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/node-liveness-probe:sha-${{ env.SHA }}
          build-args: |
            NODE_LIVENESS_PROBE_VERSION=v0.5.4
