name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:


env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  build-docker-image:
    name: Build docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        package:
          #- appbox
          #- dev-toolchain
          - gotenberg
          # - node-liveness-probe
          # - terraform
          # - artelad
          # - fuel
          # - nubit
          # - harmonytools
    steps:
      - uses: actions/checkout@v2

      - uses: benjlevesque/short-sha@v1.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.DOCKER_REGISTRY }}

      - name: Appbox
        uses: docker/build-push-action@v3
        if: ${{ matrix.package == 'appbox' }}
        with:
          push: true
          context: images/appbox
          tags: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/appbox:sha-${{ env.SHA }}

      - name: Dev toolchain
        uses: docker/build-push-action@v3
        if: ${{ matrix.package == 'dev-toolchain' }}
        with:
          push: true
          context: images/dev-toolchain
          tags: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/dev-toolchain:sha-${{ env.SHA }}
          build-args: |
            HOST_PASSWORD=${{ secrets.TOOLCHAIN_PASSWORD_HOST }}

      - name: Gotenberg
        uses: docker/build-push-action@v3
        if: ${{ matrix.package == 'gotenberg' }}
        with:
          push: true
          context: images/gotenberg
          tags: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/gotenberg:sha-${{ env.SHA }}

      - name: Node liveness probe
        uses: docker/build-push-action@v3
        if: ${{ matrix.package == 'node-liveness-probe' }}
        with:
          push: true
          context: images/node-liveness-probe
          tags: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/node-liveness-probe:sha-${{ env.SHA }}
          build-args: |
            NODE_LIVENESS_PROBE_VERSION=v0.6.1
            FLUTTER_VERSION=3.3.0
            NVM_VERSION=0.39.3
            NODE_VERSION=18.14.2

      - name: Terraform
        uses: docker/build-push-action@v3
        if: ${{ matrix.package == 'terraform' }}
        with:
          push: true
          context: images/terraform
          tags: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/terraform:sha-${{ env.SHA }}
          build-args: |
            TERRAFORM_VERSION=1.4.6
            TERRAFORM_BACKEND_GIT_VERSION=v0.1.4

      - name: Artelad
        uses: docker/build-push-action@v3
        if: ${{ matrix.package == 'artelad' }}
        with:
          push: true
          context: images/artelad
          tags: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/artelad:sha-${{ env.SHA }}

      - name: Fuel
        uses: docker/build-push-action@v3
        if: ${{ matrix.package == 'fuel' }}
        with:
          push: true
          context: images/fuel
          tags: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/fuel:sha-${{ env.SHA }}

      - name: Nubit
        uses: docker/build-push-action@v3
        if: ${{ matrix.package == 'nubit' }}
        with:
          push: true
          context: images/nubit
          tags: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/nubit:sha-${{ env.SHA }}

      - name: Harmonytools
        uses: docker/build-push-action@v3
        if: ${{ matrix.package == 'harmonytools' }}
        with:
          push: true
          context: images/harmonytools
          tags: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/harmonytools:sha-${{ env.SHA }}


